In [15]:
from bitstring_utils import *
from train_bit_model import *
%load_ext autoreload
%autoreload 2

COMET INFO: Experiment is live on comet.ml https://www.comet.ml/clrkwng/bitstr-model/9a473d9764d34870a3c9ff751eb7cb9d



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
train_bools, test_bools = get_train_test_split(2, 3)

In [20]:

test_model(np.array([0,0,0,0,0,0,0,0,0,0]))

COMET INFO: Experiment is live on comet.ml https://www.comet.ml/clrkwng/bitstr-model/845e8e8dd7ce454180e394bd935db6c5



-15.492136001586914

In [11]:
test_bools

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [6]:
get_train_data(600)

(array([[ 0,  1,  2, ...,  7, 18,  9],
        [ 0,  1, 12, ..., 17, 18, 19],
        [10, 11, 12, ...,  7, 18, 19],
        ...,
        [ 0,  1,  2, ..., 17, 18, 19],
        [ 0,  1, 12, ..., 17, 18, 19],
        [ 0,  1,  2, ...,  7, 18, 19]]),
 array([ 288,  900,  855,  700,  781,  424,  268,  886,  793,  908,  632,
          80,  160,  502,   42,   69,  686,  128,  986,  414,  476,  244,
         486,   81,  757,  336,  256,  137,   11,  636,  734,  915,  905,
         106,  487,  807,  498,  398,  611, 1000,  208,  808,  973,  501,
         981,  961,  489,  153,  255,  577,  508,  683,  132,  346,  608,
         754,  374,  591,  454,  644,  156,  306,  916,  732,  828,  993,
         232,  593,  141,   23,   58,  463,  154,  585,  225,  431,  345,
         965,  982,  992,  146,  211,  638,  176,   39,  708,  969,  855,
         218,  294,  646,  441,  509,  764,  613,  557,  727,  762,  646,
         936,  750,   20,  507,  222,  437,  530,  763,  540,  488,  112,
         17

In [2]:
get_all_bitstrings(10)

[(0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
 (0, 0, 0, 0, 0, 0, 0, 0, 0, 1),
 (0, 0, 0, 0, 0, 0, 0, 0, 1, 0),
 (0, 0, 0, 0, 0, 0, 0, 0, 1, 1),
 (0, 0, 0, 0, 0, 0, 0, 1, 0, 0),
 (0, 0, 0, 0, 0, 0, 0, 1, 0, 1),
 (0, 0, 0, 0, 0, 0, 0, 1, 1, 0),
 (0, 0, 0, 0, 0, 0, 0, 1, 1, 1),
 (0, 0, 0, 0, 0, 0, 1, 0, 0, 0),
 (0, 0, 0, 0, 0, 0, 1, 0, 0, 1),
 (0, 0, 0, 0, 0, 0, 1, 0, 1, 0),
 (0, 0, 0, 0, 0, 0, 1, 0, 1, 1),
 (0, 0, 0, 0, 0, 0, 1, 1, 0, 0),
 (0, 0, 0, 0, 0, 0, 1, 1, 0, 1),
 (0, 0, 0, 0, 0, 0, 1, 1, 1, 0),
 (0, 0, 0, 0, 0, 0, 1, 1, 1, 1),
 (0, 0, 0, 0, 0, 1, 0, 0, 0, 0),
 (0, 0, 0, 0, 0, 1, 0, 0, 0, 1),
 (0, 0, 0, 0, 0, 1, 0, 0, 1, 0),
 (0, 0, 0, 0, 0, 1, 0, 0, 1, 1),
 (0, 0, 0, 0, 0, 1, 0, 1, 0, 0),
 (0, 0, 0, 0, 0, 1, 0, 1, 0, 1),
 (0, 0, 0, 0, 0, 1, 0, 1, 1, 0),
 (0, 0, 0, 0, 0, 1, 0, 1, 1, 1),
 (0, 0, 0, 0, 0, 1, 1, 0, 0, 0),
 (0, 0, 0, 0, 0, 1, 1, 0, 0, 1),
 (0, 0, 0, 0, 0, 1, 1, 0, 1, 0),
 (0, 0, 0, 0, 0, 1, 1, 0, 1, 1),
 (0, 0, 0, 0, 0, 1, 1, 1, 0, 0),
 (0, 0, 0, 0, 0, 1, 1, 1, 0, 1),
 (0, 0, 0,